name: github pages

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: yarn install

    - name: Fix vue-adsense
      run: |
        sed -i -e "s/module.exports\ =\ VueAdsense/export default VueAdsense/g" node_modules/vue-adsense/main.js

    - name: Build
      run: yarn build

    - name: Add cname file
      run: cp CNAME ./dist/

    - name: Deploy only from develop branch
      uses: peaceiris/actions-gh-pages@v3
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./dist
      if: github.event_name == 'push'
